import * as React from 'react';
import type { TableContextShape } from './useTable';

// Memoizes the context object on the union of its inputs so consumers
// don't re-render when TableImpl re-renders for unrelated reasons. Every
// field flows straight through — this hook exists to keep TableImpl free
// of a 50-entry useMemo declaration.
export function useTableContextValue<TRecord, TRowData>(input: TableContextShape<TRecord, TRowData>): TableContextShape<TRecord, TRowData> {
  const {
    table,
    props,
    registry,
    testIdPrefix,
    mergedColumns,
    mergedLeafColumns,
    renderedLeafColumns,
    resolvedRows,
    rowByKey,
    rowDataTypeMap,
    classMap,
    styleMap,
    rootEditableConfig,
    expanded,
    editingCell,
    editingRowKey,
    editValues,
    editErrors,
    internalCellValues,
    sorting,
    columnSizing,
    columnPinning,
    tableSortDirections,
    applySortingChange,
    moveColumnByKeyboard,
    moveRowByKeyboard,
  } = input;
  return React.useMemo<TableContextShape<TRecord, TRowData>>(
    () => ({
      table,
      props,
      registry,
      testIdPrefix,
      mergedColumns,
      mergedLeafColumns,
      renderedLeafColumns,
      resolvedRows,
      rowByKey,
      rowDataTypeMap,
      classMap,
      styleMap,
      rootEditableConfig,
      expanded,
      editingCell,
      editingRowKey,
      editValues,
      editErrors,
      internalCellValues,
      sorting,
      columnSizing,
      columnPinning,
      tableSortDirections,
      applySortingChange,
      moveColumnByKeyboard,
      moveRowByKeyboard,
    }),
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [
      table,
      props,
      registry,
      testIdPrefix,
      mergedColumns,
      mergedLeafColumns,
      renderedLeafColumns,
      resolvedRows,
      rowByKey,
      rowDataTypeMap,
      classMap,
      styleMap,
      rootEditableConfig,
      expanded,
      editingCell,
      editingRowKey,
      editValues,
      editErrors,
      internalCellValues,
      sorting,
      columnSizing,
      columnPinning,
    ],
  );
}
