/**
 * The reference of every widget and field the library registers: the one `ui:widget` name, its aliases, the
 * control it adapts, the schema it binds to, the `ui:options` it reads and the value it stores. It is plain data:
 * the DynamicForm docs page draws it, a test checks it against `appWidgets` and `appFields`, and a host can
 * read it (a form builder listing the available controls).
 *
 * Every widget also reads the shared options: `size` and `variant` (field-shaped controls), `layout`
 * (`vertical` | `horizontal`), `labelActionKey`, `description`, `help`, `placeholder`; for the whole form set
 * them once in `ui:globalOptions`.
 */
export interface WidgetCatalogEntry {
  /** The name to write in `ui:widget` (or `ui:field`). */
  name: string;
  /** The registered component. */
  widget: string;
  /** Other registered names: the component's own name and the RJSF default names it replaces. */
  aliases: string[];
  /** The library control it adapts. */
  control: string;
  /** The JSON Schema type and format it binds to. */
  schema: string;
  /** The `ui:options` it reads, beyond the shared ones. */
  options: string;
  /** The shape of the stored value. */
  value: string;
}

export const widgetCatalog: WidgetCatalogEntry[] = [
  {
    name: 'text',
    widget: 'TextWidget',
    aliases: ['TextWidget', 'email', 'url', 'EmailWidget', 'URLWidget'],
    control: 'InputPrimitive',
    schema: 'string; format email, uri set the input type',
    options: 'inputType, inputMode, autocomplete, commitOnEnter, emptyValue',
    value: 'string',
  },
  {
    name: 'password',
    widget: 'PasswordWidget',
    aliases: ['PasswordWidget'],
    control: 'PasswordInputPrimitive',
    schema: 'string',
    options: 'toggleable (default true), autocomplete (current-password | new-password)',
    value: 'string',
  },
  {
    name: 'textarea',
    widget: 'TextareaWidget',
    aliases: ['TextareaWidget'],
    control: 'TextareaPrimitive',
    schema: 'string',
    options: 'rows (default 5)',
    value: 'string',
  },
  {
    name: 'select',
    widget: 'SelectWidget',
    aliases: ['SelectWidget'],
    control: 'SelectPrimitive',
    schema: 'string with enum / oneOf',
    options: 'optionSetKey, footerActionKey, searchable, placeholder',
    value: 'string',
  },
  {
    name: 'combobox',
    widget: 'ComboboxWidget',
    aliases: ['ComboboxWidget'],
    control: 'SelectPrimitive (searchable)',
    schema: 'string with enum / oneOf',
    options: 'optionSetKey, footerActionKey, placeholder',
    value: 'string',
  },
  {
    name: 'multiSelect',
    widget: 'MultiSelectWidget',
    aliases: ['MultiSelectWidget'],
    control: 'MultiSelectPrimitive',
    schema: 'array of enum / oneOf, uniqueItems; maxItems',
    options: 'optionSetKey, searchable',
    value: 'string[]',
  },
  {
    name: 'radio',
    widget: 'RadioWidget',
    aliases: ['RadioWidget'],
    control: 'RadioPrimitive',
    schema: 'string with enum / oneOf',
    options: 'inline, appearance (plain | card), optionDescriptions, enumDisabled, optionSetKey',
    value: 'string',
  },
  {
    name: 'checkbox',
    widget: 'CheckboxWidget',
    aliases: ['CheckboxWidget'],
    control: 'CheckboxPrimitive',
    schema: 'boolean (the default for it)',
    options: 'label: false',
    value: 'boolean',
  },
  {
    name: 'checkboxes',
    widget: 'CheckboxesWidget',
    aliases: ['CheckboxesWidget'],
    control: 'CheckboxGroupPrimitive',
    schema: 'array of enum / oneOf, uniqueItems',
    options: 'inline, optionDescriptions, enumDisabled, optionSetKey',
    value: 'string[]',
  },
  {
    name: 'switch',
    widget: 'SwitchWidget',
    aliases: ['SwitchWidget'],
    control: 'SwitchPrimitive',
    schema: 'boolean',
    options: 'none',
    value: 'boolean',
  },
  {
    name: 'segmented',
    widget: 'SegmentedWidget',
    aliases: ['SegmentedWidget'],
    control: 'SegmentedPrimitive',
    schema: 'string with enum / oneOf (one choice); array of them, uniqueItems, minItems (several)',
    options: 'appearance (pill | control), enumDisabled, optionSetKey',
    value: 'string, or string[] for an array schema',
  },
  {
    name: 'range',
    widget: 'RangeWidget',
    aliases: ['RangeWidget'],
    control: 'SliderPrimitive',
    schema:
      'number / integer with minimum, maximum, multipleOf (one thumb); array of two such numbers (a from-to range)',
    options: 'step, minStepsBetweenThumbs, thumbLabels',
    value: 'number, or [number, number] for an array schema',
  },
  {
    name: 'stepper',
    widget: 'StepperWidget',
    aliases: ['StepperWidget'],
    control: 'StepperPrimitive',
    schema: 'integer / number with minimum, maximum, multipleOf',
    options: 'step, unit, unitPlural, iconKey',
    value: 'number',
  },
  {
    name: 'numberInput',
    widget: 'NumberInputWidget',
    aliases: ['NumberInputWidget', 'UpDownWidget'],
    control: 'NumberInputPrimitive',
    schema: 'number / integer with minimum, maximum, multipleOf',
    options: 'decimals, thousandSeparator, prefix, suffix',
    value: 'number; empty is undefined',
  },
  {
    name: 'currency',
    widget: 'CurrencyWidget',
    aliases: ['CurrencyWidget'],
    control: 'CurrencyInputPrimitive',
    schema: 'number',
    options: 'currency (default USD), locale',
    value: 'number; empty is undefined',
  },
  {
    name: 'phone',
    widget: 'PhoneWidget',
    aliases: ['PhoneWidget', 'TelWidget'],
    control: 'PhoneInputPrimitive',
    schema: 'string',
    options: 'defaultDialCode',
    value: 'string',
  },
  {
    name: 'otp',
    widget: 'InputOTPWidget',
    aliases: ['InputOTPWidget'],
    control: 'InputOTPPrimitive',
    schema: 'string, maxLength',
    options: 'length (default 6)',
    value: 'string',
  },
  {
    name: 'tags',
    widget: 'TagInputWidget',
    aliases: ['TagInputWidget'],
    control: 'TagInputPrimitive',
    schema: 'array of string; maxItems',
    options: 'maxItems',
    value: 'string[]',
  },
  {
    name: 'date',
    widget: 'DateWidget',
    aliases: ['DateWidget'],
    control: 'DatePickerPrimitive (single)',
    schema: 'string, format date',
    options: 'min, max (YYYY-MM-DD), placeholder',
    value: 'YYYY-MM-DD',
  },
  {
    name: 'calendar',
    widget: 'CalendarWidget',
    aliases: ['CalendarWidget'],
    control: 'CalendarPrimitive',
    schema: 'string, format date',
    options: 'min, max (YYYY-MM-DD)',
    value: 'YYYY-MM-DD',
  },
  {
    name: 'dateTime',
    widget: 'DateTimeWidget',
    aliases: ['DateTimeWidget'],
    control: 'DateTimePickerPrimitive',
    schema: 'string, format date-time',
    options: 'min, max (YYYY-MM-DD), storage (local | instant)',
    value: 'local ISO string, or an ISO instant (Z) with storage: instant; cleared is undefined',
  },
  {
    name: 'time',
    widget: 'TimeWidget',
    aliases: ['TimeWidget'],
    control: 'TimePickerPrimitive',
    schema: 'string, format time',
    options: 'min, max (HH:MM), step',
    value: 'HH:MM',
  },
  {
    name: 'color',
    widget: 'ColorWidget',
    aliases: ['ColorWidget'],
    control: 'ColorPickerPrimitive',
    schema: 'string, format color',
    options: 'presets',
    value: '#rrggbb',
  },
  {
    name: 'file',
    widget: 'FileUploadWidget',
    aliases: ['FileUploadWidget', 'FileWidget'],
    control: 'FileUploadPrimitive',
    schema: 'any (validated by Zod) or string, format data-url; array for several',
    options:
      'mode (file | data-url | name), appearance (dropzone | button), accept, maxSize, maxFiles',
    value: 'File (default), data: string or name; an array of them for an array schema',
  },
  {
    name: 'richText',
    widget: 'RichTextWidget',
    aliases: ['RichTextWidget'],
    control: 'RichTextPrimitive',
    schema: 'string',
    options: 'none',
    value: 'HTML string',
  },
  {
    name: 'rating',
    widget: 'RatingWidget',
    aliases: ['RatingWidget'],
    control: 'RatePrimitive',
    schema: 'integer, minimum, maximum (the number of marks)',
    options: 'count',
    value: 'number; cleared is undefined',
  },
  {
    name: 'autocomplete',
    widget: 'AutoCompleteWidget',
    aliases: ['AutoCompleteWidget'],
    control: 'AutoCompletePrimitive',
    schema: 'string; examples are the suggestions',
    options: 'optionSetKey, placeholder',
    value: 'string (any text)',
  },
  {
    name: 'mentions',
    widget: 'MentionsWidget',
    aliases: ['MentionsWidget'],
    control: 'MentionsPrimitive',
    schema: 'string',
    options: 'optionSetKey, trigger (default @), rows',
    value: 'string (plain text)',
  },
  {
    name: 'cascader',
    widget: 'CascaderWidget',
    aliases: ['CascaderWidget'],
    control: 'CascaderPrimitive',
    schema: 'array of string',
    options: 'optionTreeKey or tree, changeOnSelect, displaySeparator, placeholder',
    value: 'string[] (the path)',
  },
  {
    name: 'treeSelect',
    widget: 'TreeSelectWidget',
    aliases: ['TreeSelectWidget'],
    control: 'TreeSelectPrimitive',
    schema: 'string (one node); array of string (several)',
    options: 'optionTreeKey or tree, selectableParents, defaultExpandAll, placeholder',
    value: 'string, or string[] for an array schema',
  },
  {
    name: 'transfer',
    widget: 'TransferWidget',
    aliases: ['TransferWidget'],
    control: 'TransferPrimitive',
    schema: 'array of enum / oneOf, uniqueItems',
    options: 'optionSetKey, searchable, oneWay',
    value: 'string[] (keys, in the order moved)',
  },
  {
    name: 'composer',
    widget: 'ComposerWidget',
    aliases: ['ComposerWidget'],
    control: 'Composer',
    schema: 'string',
    options: 'appearance (stacked | pill), maxHeight',
    value: 'string (the draft)',
  },
  {
    name: 'feedbackReasons',
    widget: 'FeedbackReasonsWidget',
    aliases: ['FeedbackReasonsWidget'],
    control: 'FeedbackPanel (reason chips)',
    schema: 'array of enum / oneOf, uniqueItems',
    options: 'optionSetKey',
    value: 'string[] (reason ids)',
  },
  {
    name: 'modelPicker',
    widget: 'ModelPickerWidget',
    aliases: ['ModelPickerWidget'],
    control: 'ModelPicker',
    schema: 'string',
    options: 'modelSetKey',
    value: 'string (the model id)',
  },
  {
    name: 'hidden',
    widget: 'HiddenWidget',
    aliases: ['HiddenWidget'],
    control: 'a hidden input',
    schema: 'any scalar',
    options: 'none',
    value: 'unchanged',
  },
  {
    name: 'derivedText',
    widget: 'DerivedTextWidget',
    aliases: ['DerivedTextWidget'],
    control: 'text from formContext.derived',
    schema: 'any; never read or written',
    options: 'derivedKey, tone',
    value: 'none (not submitted)',
  },
  {
    name: 'iconToolbar',
    widget: 'IconToolbarWidget',
    aliases: ['IconToolbarWidget'],
    control: 'IconButton / Button row',
    schema: 'any; never read or written',
    options: 'actions: [{ actionKey, variant }]',
    value: 'none (not submitted)',
  },
];

/** Fields, chosen with `ui:field`: a whole schema node (an object value, or no value). */
export const fieldCatalog: WidgetCatalogEntry[] = [
  {
    name: 'dateRange',
    widget: 'DateRangeField',
    aliases: ['DateRangeField'],
    control: 'DatePickerPrimitive (range)',
    schema: 'object with from and to, each string, format date',
    options: 'min, max (YYYY-MM-DD), placeholder',
    value: '{ from: YYYY-MM-DD, to: YYYY-MM-DD }',
  },
  {
    name: 'staticPanel',
    widget: 'StaticPanelField',
    aliases: ['StaticPanelField'],
    control: 'text from formContext.derived',
    schema: 'any; never read or written',
    options: 'panelKey, lines',
    value: 'none (not submitted)',
  },
];
