// Deferred accessibility violations (U43): story -> axe rule ids that fail today and are not fixed yet.
// Keys are `<story title>::<story name>` (for example `omni-ui-components/Badge::Default`).
// `pnpm test:a11y` runs axe on every story in dark and light and fails on any violation NOT listed here, so new
// regressions fail. Delete an entry once its story is fixed. The reason for each rule is in A11Y_DEFERRED_REASONS.

export const A11Y_DEFERRED_REASONS: Record<string, string> = {
  'color-contrast':
    'Solid primary fills carry white text at about 4.0:1 on #1677ff (brand blue; needs a darker fill token, an owner decision); the rest are small tone tokens (panel/tone/see-through/syntax) below 4.5:1.',
  'aria-allowed-attr':
    'aria-required on a button/div/span without a role that supports it (picker triggers, slider, stepper, rich text); fix is role="combobox" on the triggers, which changes role queries for consumers.',
  'aria-input-field-name': 'Slider thumbs and rich-text editors have no accessible name; needs a labels entry or a labelling prop.',
  label: 'Stand-alone OTP, time and tag inputs rendered by a story without a visible label; needs an ariaLabel prop or a story label.',
  'nested-interactive': 'Picker/multi-select trigger buttons contain focusable clear or chip controls; needs the clear control moved out of the button.',
  'scrollable-region-focusable': 'Scrollable regions with no focusable child; needs tabIndex=0 and a name on the scroll body.',
  'button-name': 'Icon-only buttons without a name (Carousel arrows, Checkbox widget); needs labels props.',
  'landmark-unique': 'Repeated landmarks (nav, section, header) without distinguishing names inside one story.',
  'empty-table-header': 'Selection, drag and expand columns have an empty th; needs a visually hidden header label from labels.',
  'aria-allowed-role': 'role="combobox" on a textarea is not allowed (Composer); needs a different pattern.',
  'label-title-only': 'Inputs named only by title/placeholder (OTP, tag input).',
  'aria-dialog-name': 'Dialog/popover without a name (Tour); needs aria-labelledby the step title.',
  'landmark-no-duplicate-banner': 'Several header elements inside one story page.',
  'heading-order': 'h5 follows no h4 in the dynamic form array template.',
  'aria-required-children': 'Empty listbox ("Nothing matches") has no options.',
  'select-name': 'Native select in Cascader has no name.',
};

export const A11Y_DEFERRED: Record<string, readonly string[]> = {
  'Getting Started/Component Overview::Component Overview': ['aria-allowed-attr', 'aria-allowed-role', 'aria-input-field-name', 'aria-required-children', 'button-name', 'color-contrast', 'label', 'label-title-only', 'landmark-unique', 'nested-interactive', 'scrollable-region-focusable', 'select-name'],
  'Getting Started/Table Overview::Table Component Overview': ['color-contrast', 'empty-table-header', 'landmark-unique', 'scrollable-region-focusable'],
  'dynamic-form/DynamicForm::Add Address': ['color-contrast'],
  'dynamic-form/DynamicForm::Api Error': ['aria-allowed-attr', 'aria-input-field-name', 'button-name', 'color-contrast', 'heading-order'],
  'dynamic-form/DynamicForm::Async Submit': ['aria-allowed-attr', 'aria-input-field-name', 'button-name', 'color-contrast', 'heading-order'],
  'dynamic-form/DynamicForm::Automation Text Fields': ['color-contrast'],
  'dynamic-form/DynamicForm::Kitchen Sink': ['aria-allowed-attr', 'aria-input-field-name', 'button-name', 'color-contrast', 'heading-order'],
  'dynamic-form/DynamicForm::Validation Errors': ['color-contrast'],
  'dynamic-form/Showcase/NewCompany::Default': ['color-contrast'],
  'dynamic-form/Showcase/NewContact::Default': ['color-contrast'],
  'dynamic-form/Showcase/NewExpense::Default': ['aria-allowed-attr', 'color-contrast', 'nested-interactive'],
  'dynamic-form/Showcase/NewTimesheet::Default': ['color-contrast'],
  'dynamic-form/widgets/CheckboxWidget::Plain': ['button-name'],
  'dynamic-form/widgets/CheckboxWidget::Prefilled': ['button-name'],
  'dynamic-form/widgets/CheckboxWidget::Validation Error': ['button-name', 'color-contrast'],
  'dynamic-form/widgets/CheckboxesWidget::Validation Error': ['color-contrast'],
  'dynamic-form/widgets/ColorWidget::Disabled': ['aria-allowed-attr'],
  'dynamic-form/widgets/ColorWidget::Plain': ['aria-allowed-attr'],
  'dynamic-form/widgets/ColorWidget::Red': ['aria-allowed-attr'],
  'dynamic-form/widgets/DateTimeWidget::Plain': ['aria-allowed-attr', 'label'],
  'dynamic-form/widgets/DateTimeWidget::Prefilled': ['aria-allowed-attr', 'label', 'nested-interactive'],
  'dynamic-form/widgets/DateWidget::Disabled': ['aria-allowed-attr'],
  'dynamic-form/widgets/DateWidget::Plain': ['aria-allowed-attr'],
  'dynamic-form/widgets/DateWidget::Prefilled': ['aria-allowed-attr', 'nested-interactive'],
  'dynamic-form/widgets/DerivedTextWidget::Success Tone': ['color-contrast'],
  'dynamic-form/widgets/MultiSelectWidget::Plain': ['aria-allowed-attr'],
  'dynamic-form/widgets/MultiSelectWidget::Prefilled': ['aria-allowed-attr', 'nested-interactive'],
  'dynamic-form/widgets/MultiSelectWidget::Searchable': ['aria-allowed-attr'],
  'dynamic-form/widgets/RadioWidget::Validation Error': ['color-contrast'],
  'dynamic-form/widgets/RangeWidget::Disabled': ['aria-input-field-name'],
  'dynamic-form/widgets/RangeWidget::Fine Step': ['aria-input-field-name'],
  'dynamic-form/widgets/RangeWidget::Plain': ['aria-input-field-name'],
  'dynamic-form/widgets/RangeWidget::Prefilled': ['aria-input-field-name'],
  'dynamic-form/widgets/RangeWidget::With Description': ['aria-input-field-name'],
  'dynamic-form/widgets/RichTextWidget::Plain': ['aria-allowed-attr', 'aria-input-field-name'],
  'dynamic-form/widgets/RichTextWidget::Prefilled': ['aria-allowed-attr', 'aria-input-field-name'],
  'dynamic-form/widgets/SegmentedWidget::Plain': ['color-contrast'],
  'dynamic-form/widgets/SegmentedWidget::Two Options': ['color-contrast'],
  'dynamic-form/widgets/SegmentedWidget::Validation Error': ['color-contrast'],
  'dynamic-form/widgets/SelectWidget::Validation Error': ['color-contrast'],
  'dynamic-form/widgets/StepperWidget::Disabled': ['color-contrast'],
  'dynamic-form/widgets/TextWidget::Validation Error': ['color-contrast'],
  'dynamic-form/widgets/TextareaWidget::Validation Error': ['color-contrast'],
  'omni-ui-components/ActionMenu::Answer Style Scrolling': ['scrollable-region-focusable'],
  'omni-ui-components/Affix::With Bottom Offset': ['scrollable-region-focusable'],
  'omni-ui-components/Badge::Default': ['color-contrast'],
  'omni-ui-components/Badge::Destructive': ['color-contrast'],
  'omni-ui-components/Badge::Matrix': ['color-contrast'],
  'omni-ui-components/Button::Default': ['color-contrast'],
  'omni-ui-components/Button::Destructive': ['color-contrast'],
  'omni-ui-components/Button::Fill Icon': ['color-contrast'],
  'omni-ui-components/Button::Native footer actions': ['color-contrast'],
  'omni-ui-components/Button::Sizes Matrix': ['color-contrast'],
  'omni-ui-components/Button::Tone Matrix': ['color-contrast'],
  'omni-ui-components/Button::With Leading Icon': ['color-contrast'],
  'omni-ui-components/Button::With Trailing Icon': ['color-contrast'],
  'omni-ui-components/Card::Default': ['color-contrast'],
  'omni-ui-components/Carousel::Default': ['button-name'],
  'omni-ui-components/Carousel::Two Slides': ['button-name'],
  'omni-ui-components/Cascader::Default': ['select-name'],
  'omni-ui-components/Checkbox::With Error': ['color-contrast'],
  'omni-ui-components/CheckboxGroup::With Error': ['color-contrast'],
  'omni-ui-components/ColorPicker::With Error': ['color-contrast'],
  'omni-ui-components/CommandPopover::Default': ['color-contrast'],
  'omni-ui-components/CommandPopover::Mentions': ['color-contrast'],
  'omni-ui-components/CommandPopover::Not Clipped In Portal': ['color-contrast'],
  'omni-ui-components/CommandPopover::Nothing Matches': ['aria-required-children'],
  'omni-ui-components/Composer::Auto Grow': ['aria-allowed-role'],
  'omni-ui-components/Composer::See Through': ['aria-allowed-role', 'color-contrast'],
  'omni-ui-components/ConversationTranscript::Chat Reply': ['color-contrast'],
  'omni-ui-components/ConversationTranscript::Streaming': ['color-contrast'],
  'omni-ui-components/DataPrivacyPanel::Activity Log': ['color-contrast'],
  'omni-ui-components/DataPrivacyPanel::Default': ['color-contrast'],
  'omni-ui-components/DataPrivacyPanel::Delete Needs Confirmation': ['aria-dialog-name', 'color-contrast'],
  'omni-ui-components/DataPrivacyPanel::Log Empty': ['color-contrast'],
  'omni-ui-components/DataPrivacyPanel::Log Loading': ['color-contrast'],
  'omni-ui-components/DataPrivacyPanel::Log Open': ['color-contrast'],
  'omni-ui-components/DataPrivacyPanel::Log Scrolls': ['color-contrast', 'scrollable-region-focusable'],
  'omni-ui-components/DataPrivacyPanel::Retention Only': ['color-contrast'],
  'omni-ui-components/DatePicker::Prefilled': ['nested-interactive'],
  'omni-ui-components/DatePicker::Range Mode': ['nested-interactive'],
  'omni-ui-components/DatePicker::Required': ['aria-allowed-attr'],
  'omni-ui-components/DatePicker::With Error': ['color-contrast'],
  'omni-ui-components/DateTimePicker::Default': ['label'],
  'omni-ui-components/DateTimePicker::Disabled': ['label'],
  'omni-ui-components/DateTimePicker::Prefilled': ['label', 'nested-interactive'],
  'omni-ui-components/DateTimePicker::Required': ['aria-allowed-attr', 'label'],
  'omni-ui-components/DateTimePicker::With Error': ['color-contrast', 'label'],
  'omni-ui-components/DictationBar::In Composer': ['aria-allowed-role'],
  'omni-ui-components/DiffReview::Checklist Two Changes': ['color-contrast'],
  'omni-ui-components/DiffReview::Default': ['color-contrast'],
  'omni-ui-components/DiffReview::Every Status': ['color-contrast', 'landmark-unique'],
  'omni-ui-components/DiffReview::Fallback When Empty': ['color-contrast'],
  'omni-ui-components/DiffReview::Keyboard Tabs': ['color-contrast'],
  'omni-ui-components/DiffReview::Long Diff': ['color-contrast'],
  'omni-ui-components/DiffReview::Translated Labels': ['color-contrast'],
  'omni-ui-components/DiffReview::With And Without Highlighting': ['landmark-unique'],
  'omni-ui-components/Drawer::Default': ['color-contrast'],
  'omni-ui-components/EmailInput::With Error': ['color-contrast'],
  'omni-ui-components/Empty::Tile Matrix': ['color-contrast'],
  'omni-ui-components/Empty::Tile With Title And Action': ['color-contrast'],
  'omni-ui-components/ErrorCard::Default': ['color-contrast'],
  'omni-ui-components/ErrorCard::Retry Disabled': ['color-contrast'],
  'omni-ui-components/FeedbackPanel::Default': ['color-contrast'],
  'omni-ui-components/FeedbackPanel::Two Chosen': ['color-contrast'],
  'omni-ui-components/FileUpload::Disabled': ['color-contrast'],
  'omni-ui-components/FileUpload::With Error': ['color-contrast'],
  'omni-ui-components/FloatButton::Text Button': ['color-contrast'],
  'omni-ui-components/Form::Add Address': ['color-contrast'],
  'omni-ui-components/Form::Api Error': ['aria-allowed-attr', 'aria-input-field-name', 'color-contrast', 'label'],
  'omni-ui-components/Form::Async Submit': ['aria-allowed-attr', 'aria-input-field-name', 'color-contrast', 'label'],
  'omni-ui-components/Form::Contact': ['color-contrast'],
  'omni-ui-components/Form::Disabled': ['aria-allowed-attr', 'aria-input-field-name', 'color-contrast', 'label'],
  'omni-ui-components/Form::Kitchen Sink': ['aria-allowed-attr', 'aria-input-field-name', 'color-contrast', 'label'],
  'omni-ui-components/Form::Prefilled': ['aria-allowed-attr', 'aria-input-field-name', 'color-contrast', 'label'],
  'omni-ui-components/Form::Read Only': ['aria-allowed-attr', 'aria-input-field-name', 'color-contrast', 'label'],
  'omni-ui-components/Form::Validation Errors': ['aria-allowed-attr', 'aria-input-field-name', 'color-contrast', 'label'],
  'omni-ui-components/Input::With Error': ['color-contrast'],
  'omni-ui-components/InputOTP::Default': ['label'],
  'omni-ui-components/InputOTP::Disabled': ['label'],
  'omni-ui-components/InputOTP::Four Digit': ['label'],
  'omni-ui-components/InputOTP::Prefilled': ['label'],
  'omni-ui-components/InputOTP::With Error': ['color-contrast', 'label', 'label-title-only'],
  'omni-ui-components/IntegrationList::O Auth Accounts': ['color-contrast'],
  'omni-ui-components/Markdown::Chat Reply': ['color-contrast'],
  'omni-ui-components/Markdown::Chat Reply Streaming': ['color-contrast'],
  'omni-ui-components/Markdown::Default': ['color-contrast'],
  'omni-ui-components/Markdown::Line Numbers Wrapped': ['color-contrast'],
  'omni-ui-components/Modal::Default': ['color-contrast'],
  'omni-ui-components/Modal::Destructive': ['color-contrast'],
  'omni-ui-components/ModelPicker::Hosted Model': ['color-contrast'],
  'omni-ui-components/ModelPicker::Local Only': ['color-contrast'],
  'omni-ui-components/ModelPicker::Menu Only': ['color-contrast'],
  'omni-ui-components/ModelPicker::Non Reasoning Model': ['color-contrast'],
  'omni-ui-components/ModelPicker::Open Menu': ['color-contrast'],
  'omni-ui-components/ModelPicker::Translated Labels': ['color-contrast'],
  'omni-ui-components/ModelPicker::Without Effort': ['color-contrast'],
  'omni-ui-components/MultiSelect::Disabled': ['nested-interactive'],
  'omni-ui-components/MultiSelect::Prefilled': ['nested-interactive'],
  'omni-ui-components/MultiSelect::With Error': ['color-contrast'],
  'omni-ui-components/Navigation/Wizard::Blocked Step': ['color-contrast'],
  'omni-ui-components/Navigation/Wizard::Custom Labels': ['color-contrast'],
  'omni-ui-components/Navigation/Wizard::Default': ['color-contrast'],
  'omni-ui-components/Navigation/Wizard::Start On Middle Step': ['color-contrast'],
  'omni-ui-components/NumberInput::With Error': ['color-contrast'],
  'omni-ui-components/Panel::Analysing With Stop And Dock': ['color-contrast'],
  'omni-ui-components/Panel::Ready Nothing Analysed': ['color-contrast'],
  'omni-ui-components/Panel::See Through 22': ['color-contrast'],
  'omni-ui-components/Panel::See Through 60': ['color-contrast'],
  'omni-ui-components/Panel::Three Panels': ['color-contrast'],
  'omni-ui-components/Panel::Three Panels Analysing': ['color-contrast'],
  'omni-ui-components/Panel::Three Panels At 900': ['color-contrast'],
  'omni-ui-components/PasswordInput::With Error': ['color-contrast'],
  'omni-ui-components/PhoneInput::With Error': ['color-contrast'],
  'omni-ui-components/Popconfirm::Default': ['color-contrast'],
  'omni-ui-components/Radio::With Error': ['color-contrast'],
  'omni-ui-components/RichText::Default': ['aria-input-field-name'],
  'omni-ui-components/RichText::Disabled': ['aria-input-field-name'],
  'omni-ui-components/RichText::Prefilled': ['aria-input-field-name'],
  'omni-ui-components/RichText::With Error': ['aria-input-field-name', 'color-contrast'],
  'omni-ui-components/Segmented::Default': ['color-contrast'],
  'omni-ui-components/Segmented::Horizontal Sidebar': ['color-contrast'],
  'omni-ui-components/Segmented::Required': ['color-contrast'],
  'omni-ui-components/Segmented::Two Options': ['color-contrast'],
  'omni-ui-components/Segmented::With Error': ['color-contrast'],
  'omni-ui-components/Select::Required': ['aria-allowed-attr'],
  'omni-ui-components/Select::With Error': ['color-contrast'],
  'omni-ui-components/SessionBar::End Confirm': ['aria-dialog-name', 'color-contrast'],
  'omni-ui-components/SessionBar::Paused': ['color-contrast'],
  'omni-ui-components/SessionBar::Props Only': ['color-contrast'],
  'omni-ui-components/SessionBar::See Through': ['color-contrast'],
  'omni-ui-components/SettingsDialog::Arrow Key Tabs': ['color-contrast'],
  'omni-ui-components/SettingsDialog::Danger Row': ['color-contrast'],
  'omni-ui-components/SettingsDialog::Data And Privacy Tab': ['color-contrast'],
  'omni-ui-components/SettingsDialog::Default': ['color-contrast'],
  'omni-ui-components/SettingsDialog::Setting Row Tones': ['color-contrast'],
  'omni-ui-components/SettingsDialog::Two Tabs': ['color-contrast'],
  'omni-ui-components/Showcase/Native App::Footer States (1e)': ['color-contrast'],
  'omni-ui-components/Showcase/Native App::Panels In Three States (1d)': ['color-contrast', 'landmark-unique'],
  'omni-ui-components/Showcase/Native App::Toolbar Variations (1c)': ['aria-allowed-attr'],
  'omni-ui-components/Showcase/Native App::Window 1180': ['color-contrast'],
  'omni-ui-components/Showcase/Native App::Window 900': ['color-contrast'],
  'omni-ui-components/Showcase/NewExpense::Default': ['aria-allowed-attr', 'nested-interactive'],
  'omni-ui-components/Slider::Default': ['aria-input-field-name'],
  'omni-ui-components/Slider::Disabled': ['aria-input-field-name'],
  'omni-ui-components/Slider::Fine Step': ['aria-input-field-name'],
  'omni-ui-components/Slider::Horizontal Sidebar': ['aria-input-field-name'],
  'omni-ui-components/Slider::Prefilled': ['aria-input-field-name'],
  'omni-ui-components/Slider::Required': ['aria-allowed-attr', 'aria-input-field-name'],
  'omni-ui-components/Slider::With Error': ['aria-input-field-name', 'color-contrast'],
  'omni-ui-components/Sources::Card Open': ['color-contrast'],
  'omni-ui-components/Sources::One Source': ['color-contrast'],
  'omni-ui-components/Stepper::Disabled': ['color-contrast'],
  'omni-ui-components/Stepper::Required': ['aria-allowed-attr'],
  'omni-ui-components/Stepper::With Error': ['color-contrast'],
  'omni-ui-components/Steps::Checklist': ['color-contrast'],
  'omni-ui-components/Steps::Checklist States': ['color-contrast'],
  'omni-ui-components/Steps::Default': ['color-contrast'],
  'omni-ui-components/StreamStatus::All States': ['color-contrast'],
  'omni-ui-components/StreamStatus::Default': ['color-contrast'],
  'omni-ui-components/StreamStatus::Long Running': ['color-contrast'],
  'omni-ui-components/StreamStatus::Reasoning': ['color-contrast'],
  'omni-ui-components/StreamStatus::Stall': ['color-contrast'],
  'omni-ui-components/Switch::With Error': ['color-contrast'],
  'omni-ui-components/Table/API::Table Component API': ['color-contrast'],
  'omni-ui-components/Table/DataRow::Draggable Rows': ['color-contrast', 'empty-table-header'],
  'omni-ui-components/Table/DataRow::Row States And Attributes': ['color-contrast'],
  'omni-ui-components/Table/Design Tokens::Design Tokens': ['color-contrast'],
  'omni-ui-components/Table/Expandable::Controlled Expanded Keys': ['empty-table-header'],
  'omni-ui-components/Table/Expandable::Custom Expand Icon': ['empty-table-header'],
  'omni-ui-components/Table/Expandable::Expanded Row Render': ['empty-table-header'],
  'omni-ui-components/Table/Kitchen Sink::All Features': ['color-contrast', 'empty-table-header', 'landmark-no-duplicate-banner', 'landmark-unique'],
  'omni-ui-components/Table/Pagination::Placement Variants': ['landmark-unique'],
  'omni-ui-components/Table/Selection::Disabled Rows': ['color-contrast'],
  'omni-ui-components/Table/Selection::Radio Selection': ['empty-table-header'],
  'omni-ui-components/Table/Table::Appearance Variants': ['landmark-no-duplicate-banner', 'landmark-unique'],
  'omni-ui-components/Table/Table::Empty And Loading': ['color-contrast', 'landmark-no-duplicate-banner', 'landmark-unique'],
  'omni-ui-components/Table/Virtualization::Column Virtualization': ['scrollable-region-focusable'],
  'omni-ui-components/Table/Virtualization::Pinned Columns With Virtual Columns': ['scrollable-region-focusable'],
  'omni-ui-components/Table/Virtualization::Row Virtualization': ['scrollable-region-focusable'],
  'omni-ui-components/Table/Virtualization::Sticky Header And Scroll': ['scrollable-region-focusable'],
  'omni-ui-components/Table/Virtualization::Table Ref Scroll To': ['scrollable-region-focusable'],
  'omni-ui-components/Tag::Colored': ['color-contrast'],
  'omni-ui-components/Tag::Status Set': ['color-contrast'],
  'omni-ui-components/Tag::Variant Matrix': ['color-contrast'],
  'omni-ui-components/TagInput::Disabled': ['color-contrast', 'label'],
  'omni-ui-components/TagInput::Max Items': ['label-title-only'],
  'omni-ui-components/TagInput::Prefilled': ['label'],
  'omni-ui-components/TagInput::With Error': ['color-contrast', 'label-title-only'],
  'omni-ui-components/Textarea::With Error': ['color-contrast'],
  'omni-ui-components/TimePicker::With Error': ['color-contrast'],
  'omni-ui-components/Tour::Default': ['aria-dialog-name', 'color-contrast'],
  'omni-ui-components/Tour::Second Step': ['aria-dialog-name'],
  'omni-ui-components/Transcript::Conversation': ['aria-allowed-role'],
  'omni-ui-components/Transcript::Conversation Approval': ['aria-allowed-role', 'color-contrast'],
  'omni-ui-components/Transcript::Conversation Empty': ['aria-allowed-role'],
  'omni-ui-components/Transcript::Conversation Failed': ['aria-allowed-role', 'color-contrast'],
  'omni-ui-components/Transcript::Conversation Load Earlier': ['aria-allowed-role'],
  'omni-ui-components/Transcript::Conversation See Through': ['aria-allowed-role', 'color-contrast'],
  'omni-ui-components/Transcript::Conversation Stopped': ['aria-allowed-role'],
  'omni-ui-components/Transcript::Conversation Streaming': ['aria-allowed-role'],
  'omni-ui-components/Transcript::Edited Bubble': ['color-contrast'],
  'omni-ui-components/Transcript::See Through': ['color-contrast'],
  'omni-ui-components/Typography::Editorial Block': ['color-contrast'],
  'omni-ui-components/Typography::Tone Variants': ['color-contrast'],
  'omni-ui-components/Watermark::Default': ['color-contrast'],
  'omni-ui-components/Watermark::Internal': ['color-contrast'],
};
